mm_purchase_invoice:
    resource: "@MMBundle/Controller/PurchaseInvoiceController.php"
    type:     annotation

mm_sale_invoice:
    resource: "@MMBundle/Controller/SaleInvoiceController.php"
    type:     annotation

mm_document:
    resource: "@MMBundle/Controller/DocumentController.php"
    type:     annotation

mm_equipment:
    resource: "@MMBundle/Controller/EquipmentController.php"
    type:     annotation

mm_attendance:
    resource: "@MMBundle/Controller/AttendanceController.php"
    type:     annotation

mm:
    resource: "@MMBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
