mm_attendance:
    resource: "@MMBundle/Controller/AttendanceController.php"
    type:     annotation

mm:
    resource: "@MMBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
