# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.post_voter:
        class:  AppBundle\Security\DocumentVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    app.saleinvoice_voter:
            class:  AppBundle\Security\SaleInvoiceVoter
            tags:
                - { name: security.voter }
            # small performance boost
            public: false
    app.attendance_voter:
                class:  AppBundle\Security\AttendanceVoter
                tags:
                    - { name: security.voter }
                # small performance boost
                public: false

    app.license_voter:
                    class:  AppBundle\Security\LicenseVoter
                    tags:
                        - { name: security.voter }
                    # small performance boost
                    public: false
