MMBundle\Entity\Equipment:
    type: entity
    table: null
    repositoryClass: MMBundle\Repository\EquipmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nrInwentarzowy:
            type: integer
            column: NrInwentarzowy
        nazwa:
            type: string
            length: 255
            column: Nazwa
        nrSeryjny:
            type: string
            length: 255
            column: NrSeryjny
        dataZakupu:
            type: date
            column: DataZakupu
        nrFaktury:
            type: string
            length: 255
            column: NrFaktury
        terminGwarancji:
            type: date
            column: TerminGwarancji
        wartoscNetto:
            type: float
            column: WartoscNetto
        kogoSprzet:
            type: string
            length: 255
            column: KogoSprzet
        notatki:
            type: string
            length: 255
            column: Notatki
    lifecycleCallbacks: {  }
