MMBundle\Entity\PurchaseInvoice:
    type: entity
    table: null
    repositoryClass: MMBundle\Repository\PurchaseInvoiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contractorId:
            type: integer
            column: contractor_id
        fileId:
            type: integer
            column: file_id
        taxId:
            type: integer
            column: tax_id
        title:
            type: string
            length: 255
        number:
            type: integer
        amountNetto:
            type: integer
            column: amount_netto
        amountBrutto:
            type: integer
            column: amount_brutto
    lifecycleCallbacks: {  }
