<?php

namespace MMBundle\Repository;

/**
 * AttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceRepository extends \Doctrine\ORM\EntityRepository
{

    public function filter($form) {
        $qb = $this->createQueryBuilder('d');

        if(!empty($form->get('data')->getData())) {
            $qb->orWhere('d.data = :data')
                ->setParameter('data', $form->get('data')->getData());

        }

        return $qb->getQuery();
    }
}
