<?php

namespace MMBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
	public function search($form) {
		$qb = $this->createQueryBuilder('d');
		
		if(!empty($form->get('stronyDokumentu')->getData())) {
			$qb->orWhere('d.stronyDokumentu = :str')
				->setParameter('str', $form->get('stronyDokumentu')->getData());

		}
		
		return $qb->getQuery()->getResult();		
	}


    public function filter($form) {
        $qb = $this->createQueryBuilder('d');

        if(!empty($form->get('dataDokumentu')->getData())) {
            $qb->orWhere('d.dataDokumentu = :data')
                ->setParameter('data', $form->get('dataDokumentu')->getData());

        }

        return $qb->getQuery();
    }

}
