<?php

namespace MMBundle\Repository;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use MMBundle\Entity\Equipment;
use MMBundle\Form\EquipmentType;
use MMBundle\Form\EquipmentSearchType;

/**
 * EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends \Doctrine\ORM\EntityRepository
{
	public function search($form) {

		$qb = $this->createQueryBuilder('e');
		
		
		
		if(!empty($form->get('nrInwentarzowy')->getData())) {
			$qb->orWhere('e.nrInwentarzowy = :inw')
				->setParameter('inw', $form->get('nrInwentarzowy')->getData());
		}

		if(!empty($form->get('nrSeryjny')->getData())) {
			$qb->orWhere('e.nrSeryjny = :ser')
				->setParameter('ser', $form->get('nrSeryjny')->getData());

		}
		
		return $qb->getQuery()->getResult();
	}
}
