<?php

namespace MMBundle\Repository;

/**
 * licenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class licenseRepository extends \Doctrine\ORM\EntityRepository
{
}
